version: 2
jobs:
  build:
    working_directory: ~/react-native-router-flux
    docker:
      - image: circleci/node:8
    steps:
      - run:
          name: temporary-eslint-airbnb-config-install
          command: |
            git clone https://github.com/airbnb/javascript.git --branch eslint-config-airbnb-v16.1.0 --single-branch ~/airbnb-style
            cd ~/airbnb-style/ && yarn install
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run:
          name: test
          command: yarn test
      - run:
          name: linter
          command: yarn eslint
